### ISSUE TITLE
Imbalanced Data Transform always set to 'RandomUnderSampler' method

### ISSUE THREAD

**Issue by brosscle** [wwu-mmll/photonai#44]
Hi, and thanks for your work on PhotonAI !
I created an hyperpipe and added a PipelineElement about imbalanced data transformations, like explained on https://wwu-mmll.github.io/photonai/examples/imbalanced_data/ .
Unfortunately, when I look at my hyperpipe elements after the creation, I get the element `PipelineElement(method_name='RandomUnderSampler', name='ImbalancedDataTransformer')` for every selected method, event when selecting an oversampling method, which is quite embarrassing...
Do you have any idea about how to solve this issue, and effectively add the selected method as element to my hyperpipe ?
I am using version 2.1.0, maybe this issue has been addressed on version 2.2.0 ?
Thanks in advance for your help !
Clément

**Comment by lucasplagwitz** [comment]
Hi Clément,

you are absolutely right, the ImbalancedDataTransformer stays with the default parameter. Thank you for discovering this issue! To quickly reproduce the effect, here is a script to examine the transformer:

```
import warnings
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.exceptions import UndefinedMetricWarning
from imblearn.datasets import fetch_datasets
import pandas as pd

from photonai.base import Hyperpipe, PipelineElement
from photonai.optimization import Categorical


def target_relative(y_true, y_pred):
    return pd.Series(y_true).value_counts()[1]/len(y_true)


def target_absolute(y_true, y_pred):
    return len(y_true)


warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

dataset = fetch_datasets()['coil_2000']
X, y = dataset.data, dataset.target

my_pipe = Hyperpipe('balanced_pipe',
                    optimizer='grid_search',
                    metrics=['accuracy', target_relative, target_absolute],
                    best_config_metric="accuracy",
                    inner_cv=StratifiedShuffleSplit(n_splits=3, test_size=0.2),
                    verbosity=1,
                    project_folder='./tmp/')


my_pipe += PipelineElement('StandardScaler')

tested_methods = Categorical(['RandomOverSampler', 'RandomUnderSampler'])
my_pipe += PipelineElement('ImbalancedDataTransformer',
                           hyperparameters={'method_name': tested_methods},
                           test_disabled=False)
my_pipe += PipelineElement("LogisticRegression")
my_pipe.fit(X, y)


# -> test samples per strategy
test_perf = pd.DataFrame([], columns=["config", "acc", "class_distribution", "absolute_samples"])

for i, test_config_item in enumerate(my_pipe.results.outer_folds[0].tested_config_list):
    config = test_config_item.config_dict["ImbalancedDataTransformer__method_name"]
    acc = round(test_config_item.metrics_train[0].value, 3)
    relative = round(test_config_item.metrics_train[2].value, 3)
    absolute = round(test_config_item.metrics_train[4].value, 3)
    test_perf = test_perf.append(pd.Series([config, acc, relative, absolute], index=test_perf.columns),
                                 ignore_index=True)

print(test_perf)
```

A first fixed version can be found [here](https://github.com/wwu-mmll/photonai/tree/fix/imbalanced_transformer). We would be happy if you could test whether your problem is also solved in this way. With customized tests, we will then merge the branch into develop/main for a new version. 

Thanks again for opening this issue!

Best,
Lucas
